export const WFD=[
[1,"★★★","In this class the teachers will teach you the planning of your essays.","이 수업에서 교사들은 여러분에게 에세이 구성법을 가르칠 것이다."],
[2,"★★★","Her design incorporates the best aspects of architecture.","그녀의 디자인은 건축의 가장 좋은 측면들을 포함하고 있다."],
[3,"★★★","Polar regions' islands are ideal for astrophysicists and meteorologists to carry out field experiments.","극지방의 섬들은 천체물리학자와 기상학자들이 현장 실험을 수행하기에 이상적이다."],
[4,"★★★","A university degree is required for entry into various professions.","여러 전문직에 진입하려면 대학 학위가 필요하다."],
[5,"★★★","It is quite clear that our facial expressions are different across the world.","우리의 얼굴 표정이 전 세계적으로 다르다는 것은 꽤 분명하다."],
[6,"★★★","All experimental procedures are outlined in the laboratory manual.","모든 실험 절차는 실험실 매뉴얼에 설명되어 있다."],
[7,"★★★","You can find the complaint form on the website.","불만 신고 양식은 웹사이트에서 찾을 수 있다."],
[8,"★★★","There was a prize for the best student presentation.","최우수 학생 발표에 대한 상이 있었다."],
[9,"★★★","Class participation is an important part of your final grade.","수업 참여는 최종 성적의 중요한 부분이다."],
[10,"★★★","Undoubtedly, this theory has a number of limitations.","의심할 여지 없이 이 이론에는 여러 한계가 있다."],
[11,"★★★","The office hours will be changed from next term.","상담 시간은 다음 학기부터 변경될 것이다."],
[12,"★★★","We are looking for new ways to engage learners.","우리는 학습자들의 참여를 이끌어낼 새로운 방법을 찾고 있다."],
[13,"★★★","The unemployment rate has fallen to its lowest level in years.","실업률은 수년 만에 가장 낮은 수준으로 떨어졌다."],
[14,"★★★","Football is played throughout the year at the university.","대학에서는 일 년 내내 축구가 진행된다."],
[15,"★★★","Chemical reactions occur when substances combine or change.","화학 반응은 물질이 결합하거나 변화할 때 일어난다."],
[16,"★★★","The studies showed that the Hong Kong people were the most active in Asia.","그 연구들은 홍콩 사람들이 아시아에서 가장 활동적이었다는 것을 보여주었다."],
[17,"★★★","Mathematics provides a foundation for understanding and analyzing data.","수학은 데이터를 이해하고 분석하는 기초를 제공한다."],
[18,"★★★","The teacher training includes observing the classes.","교사 양성 과정에는 수업 관찰이 포함된다."],
[19,"★★★","We have a great deal of debate on that topic.","그 주제에 대해서는 많은 논쟁이 있다."],
[20,"★★★","Course work gives students the chances to thoroughly explore the subject.","코스워크는 학생들에게 그 과목을 깊이 탐구할 기회를 제공한다."],
[21,"★★★","Our courses help to improve critical thinking and independent learning skills.","우리 강좌들은 비판적 사고력과 자기주도 학습 능력을 향상시키는 데 도움을 준다."],
[22,"★★★","When attending a job interview, punctuality is the key.","취업 면접에 참석할 때 시간 엄수는 핵심이다."],
[23,"★★★","You can use your laptops in the lecture.","강의 중 노트북을 사용할 수 있다."],
[24,"★★★","You need to put these books on the table over there.","이 책들을 저쪽 테이블 위에 놓아야 한다."],
[25,"★★★","Computers used to be larger than they are now.","컴퓨터는 지금보다 예전에 더 컸다."],
[26,"★★★","It is important to plan your study time carefully.","학습 시간을 신중하게 계획하는 것이 중요하다."],
[27,"★★★","The museum is closed on the third Monday of every month.","박물관은 매달 셋째 주 월요일에 휴관한다."],
[28,"★★★","Population has a sharp rise in the recent twenty years.","최근 20년 동안 인구가 급격히 증가했다."],
[29,"★★★","Optional tutorials are offered in the final week of a term.","선택 튜토리얼은 학기 마지막 주에 제공된다."],
[30,"★★★","We encourage students to complete their applications before the deadline.","우리는 학생들이 마감일 전에 지원서를 완료하도록 권장한다."],
[31,"★★★","A good academic paper should present a clear argument.","좋은 학술 논문은 명확한 주장을 제시해야 한다."],
[32,"★★★","The rising inflation rate indicates a decrease in demand for consumer products.","상승하는 인플레이션율은 소비재 수요 감소를 나타낸다."],
[33,"★★★","The dance department stages elaborated performances each semester.","무용학과는 매 학기 정교한 공연을 무대에 올린다."],
[34,"★★★","All industries are a system of inputs, processes, outputs and feedback.","모든 산업은 투입, 과정, 산출, 피드백으로 이루어진 시스템이다."],
[35,"★★★","Strangely, people are simultaneously impressed by and skeptical of using statistics.","이상하게도 사람들은 통계 사용에 감탄하는 동시에 회의적이기도 하다."],
[36,"★★★","Please note that the seminar has now been canceled.","세미나는 현재 취소되었음을 알려드립니다."],
[37,"★★★","Classical mechanics is sometimes considered as a branch of applied mathematics.","고전 역학은 때때로 응용 수학의 한 분야로 여겨진다."],
[38,"★★★","The college operates a system of continuous assessment.","그 대학은 지속적 평가 제도를 운영한다."],
[39,"★★★","Students are advised that all the lectures today have been canceled.","학생들은 오늘의 모든 강의가 취소되었음을 안내받았다."],
[40,"★★★","Philosophy uses logic and reasons to analyze human experiences.","철학은 인간 경험을 분석하기 위해 논리와 이성을 사용한다."],
[41,"★★★","Air pollution is a serious problem all over the world.","대기 오염은 전 세계적으로 심각한 문제이다."],
[42,"★★★","Protective clothing must always be worn in the laboratory.","실험실에서는 항상 보호복을 착용해야 한다."],
[43,"★★★","Rising sea temperatures are a sign of climate change.","해수 온도 상승은 기후 변화의 징후이다."],
[44,"★★★","He wrote poetry and plays as well as scientific papers.","그는 과학 논문뿐만 아니라 시와 희곡도 썼다."],
[45,"★★★","When the root system of a plant fails, foliage suffers.","식물의 뿌리 체계가 손상되면 잎이 영향을 받는다."],
[46,"★★★","The use of mobile phones is not permitted in the library.","도서관에서는 휴대전화 사용이 허용되지 않는다."],
[47,"★★★","An effective manager is always open to new ideas.","유능한 관리자는 항상 새로운 아이디어에 열려 있다."],
[48,"★★★","A new collection of articles has just been published.","새로운 논문 모음집이 막 출판되었다."],
[49,"★★★","The farmers need to adapt to the changes of the climate.","농부들은 기후 변화에 적응해야 한다."],
[50,"★★★","Honey can be used as the food and health product.","꿀은 식품이자 건강 제품으로 사용될 수 있다."],
[51,"★★★","Currently, the growth of the economy is unpredictable.","현재 경제 성장은 예측하기 어렵다."],
[52,"★★★","Many university lectures can now be viewed on the Internet.","많은 대학 강의는 이제 인터넷으로 볼 수 있다."],
[53,"★★★","The digital camera has some advantages over traditional film.","디지털 카메라는 전통적인 필름보다 몇 가지 장점이 있다."],
[54,"★★★","Many diseases that were once serious have been eradicated.","한때 심각했던 많은 질병들이 근절되었다."],
[55,"★★★","New materials and techniques are changing the style of architecture.","새로운 재료와 기술이 건축 양식을 변화시키고 있다."],
[56,"★★★","The marine environment has been destroyed by pollution and unsustainable development.","해양 환경은 오염과 지속 불가능한 개발로 파괴되었다."],
[57,"★★★","Academic libraries across the world are steadily incorporating social media.","전 세계의 학술 도서관들이 소셜 미디어를 꾸준히 도입하고 있다."],
[58,"★★★","This course involves a combination of pure and applied mathematics.","이 강좌는 순수 수학과 응용 수학의 결합으로 이루어져 있다."],
[59,"★★★","Requests for late applications will not be accepted under any circumstances.","기한이 지난 신청은 어떠한 경우에도 받아들여지지 않는다."],
[60,"★★★","Plants are able to continue growing throughout their lives.","식물은 일생 동안 계속 성장할 수 있다."],
[61,"★★★","Food containing overabundant calories provides little or no nutritional value.","과도한 열량을 함유한 음식은 영양가가 거의 또는 전혀 없다."],
[62,"★★★","The commissioner will apportion the funds among all the authorities.","위원은 자금을 모든 기관에 배분할 것이다."],
[63,"★★★","Muscle cells bring parts of the body closer together.","근육 세포는 신체 부위들을 서로 가까이 끌어당긴다."],
[64,"★★★","Social psychology is concerned with the understanding of human behaviors.","사회심리학은 인간 행동의 이해와 관련된 학문이다."],
[65,"★★★","The chemistry building is located near the entrance to the campus.","화학관은 캠퍼스 입구 근처에 위치해 있다."],
[66,"★★★","Banks charge interest on the money they loan to their customers.","은행은 고객에게 대출한 돈에 대해 이자를 부과한다."],
[67,"★★★","Social media is criticized for causing internet addiction.","소셜 미디어는 인터넷 중독을 유발한다는 비판을 받고 있다."],
[68,"★★★","The student shop sells a range of stationery.","학생 상점은 다양한 문구류를 판매한다."],
[69,"★★★","Students must wear protective clothing provided in the medical laboratory.","학생들은 의학 실험실에서 제공된 보호복을 착용해야 한다."],
[70,"★★★","Essays and assignments are spread across the academic year.","에세이와 과제는 학년도 전반에 걸쳐 배치되어 있다."],
[71,"★★★","The area has a variety of underwater habitats and species.","그 지역에는 다양한 수중 서식지와 종들이 있다."],
[72,"★★★","Sugar is a compound, which consists of carbon, oxygen, and hydrogen.","설탕은 탄소, 산소, 수소로 이루어진 화합물이다."],
[73,"★★★","The north campus car park could be closed on Sunday.","북쪽 캠퍼스 주차장은 일요일에 폐쇄될 수 있다."],
[74,"★★★","Photography is very useful for geographical research.","사진 촬영은 지리학 연구에 매우 유용하다."],
[75,"★★★","There is a widely believed perception that engineering is for boys.","공학은 남학생을 위한 분야라는 인식이 널리 퍼져 있다."],
[76,"★★★","The library will be closed for staff training tomorrow morning.","도서관은 내일 아침 직원 연수로 문을 닫는다."],
[77,"★★★","Your ideas are discussed and debated in seminars and tutorials.","여러분의 아이디어는 세미나와 튜토리얼에서 토론되고 논의된다."],
[78,"★★★","The printers automatically print two sides of each page.","프린터는 각 페이지의 양면을 자동으로 인쇄한다."],
[79,"★★★","Make sure you choose a course that provides great career opportunities.","좋은 진로 기회를 제공하는 강좌를 선택했는지 확인해야 한다."],
[80,"★★★","Dealing with the growing population is a challenge for many governments.","증가하는 인구에 대응하는 것은 많은 정부의 과제이다."],
[81,"★★★","Distance learning allows you to develop your career around your commitments.","원격 학습은 개인 일정에 맞춰 경력을 개발할 수 있게 해 준다."],
[82,"★★★","The library plays an important role in students' lives.","도서관은 학생들의 삶에서 중요한 역할을 한다."],
[83,"★★★","Our professor is hosting the business development conference.","우리 교수님은 기업 개발 콘퍼런스를 주최하고 있다."],
[84,"★★★","Check the website if you are looking for discounted textbooks.","할인 교재를 찾고 있다면 웹사이트를 확인하라."],
[85,"★★★","Farming methods across the world have greatly developed recently.","전 세계의 농업 방식은 최근 크게 발전했다."],
[86,"★★★","The university has invested in new technologies designed to support learning.","대학은 학습을 지원하기 위한 신기술에 투자했다."],
[87,"★★★","They developed a unique approach to training their employees.","그들은 직원 교육을 위한 독창적인 접근 방식을 개발했다."],
[88,"★★★","More research is needed before any definitive conclusion is drawn.","확정적인 결론을 내리기 전에는 더 많은 연구가 필요하다."],
[89,"★★★","Several candidates will be qualified as the greatest scientists of all time.","여러 후보들이 역사상 가장 위대한 과학자로 평가될 수 있다."],
[90,"★★★","The Industrial Revolution in Europe was driven by steam technology.","유럽의 산업혁명은 증기 기술에 의해 추진되었다."],
[91,"★★★","Mature students usually adapt to university life extremely well.","성인 학생들은 보통 대학 생활에 매우 잘 적응한다."],
[92,"★★★","Take the first step by applying for a university scholarship now.","지금 대학 장학금에 지원하여 첫걸음을 내디뎌라."],
[93,"★★★","The professor took a year off to work on the book.","교수는 책 집필을 위해 1년간 휴직했다."],
[94,"★★★","Students will focus on reporting news about the changing media world.","학생들은 변화하는 미디어 세계에 관한 뉴스 보도에 집중할 것이다."],
[95,"★★★","The department has a higher-than-normal proportion of postgraduate students.","그 학과는 일반보다 대학원생 비율이 높다."],
[96,"★★★","Traffic is the main cause of air pollution in many cities.","교통은 많은 도시에서 대기 오염의 주요 원인이다."],
[97,"★★★","The lecture tomorrow will discuss the educational policy in the United States.","내일 강의는 미국의 교육 정책을 논의할 것이다."],
[98,"★★★","The business policy seminar includes an internship with a local firm.","경영 정책 세미나는 지역 기업에서의 인턴십을 포함한다."],
[99,"★★★","Most scientists believe that climate change threatens lives on the earth.","대부분의 과학자들은 기후 변화가 지구상의 생명을 위협한다고 믿는다."],
[100,"★★★","He landed his job in a very prestigious law firm.","그는 매우 명망 있는 로펌에 취직했다."],
[101,"★★★","The economic strength of the early Roman Republic will be examined.","초기 로마 공화국의 경제력이 검토될 것이다."],
[102,"★★★","Despite their differences, all forms of life share the same characteristics.","차이점에도 불구하고 모든 생명체는 같은 특성을 공유한다."],
[103,"★★★","An introduction is an essential element of a presentation.","서론은 발표의 필수적인 요소이다."],
[104,"★★★","Education and training provide important skills for the labor force.","교육과 훈련은 노동력에 중요한 기술을 제공한다."],
[105,"★★★","Building trust is not something that can be achieved overnight.","신뢰를 쌓는 것은 하룻밤 사이에 이룰 수 있는 일이 아니다."],
[106,"★★★","Some people believe that education should be free for all.","일부 사람들은 교육이 모두에게 무료여야 한다고 믿는다."],
[107,"★★★","One of the election promises is to decrease the income tax.","선거 공약 중 하나는 소득세를 인하하는 것이다."],
[108,"★★★","Those who are considering a career in marketing should attend the talk.","마케팅 분야의 진로를 고려하는 사람들은 그 강연에 참석해야 한다."],
[109,"★★★","There is a pharmacy on campus near the bookstore.","캠퍼스에는 서점 근처에 약국이 있다."],
[110,"★★★","The marketing budget has been doubled since the beginning of the year.","마케팅 예산은 연초 이후 두 배로 늘어났다."],
[111,"★★★","Experts are now able to forecast weather over much longer periods.","전문가들은 이제 훨씬 더 긴 기간의 날씨를 예측할 수 있다."],
[112,"★★★","Students are encouraged to monitor their own attendance.","학생들은 자신의 출석을 관리하도록 권장된다."],
[113,"★★★","Collaboration between departments is a feature of successful companies.","부서 간 협력은 성공적인 기업의 특징이다."],
[114,"★★★","The ability to work with fellow students cannot be stressed enough.","동료 학생들과 함께 일하는 능력은 아무리 강조해도 지나치지 않다."],
[115,"★★★","You will acquire many skills during the academic studies.","학업 과정 동안 많은 기술을 습득하게 될 것이다."],
[116,"★★★","Studies show there is a positive correlation between two variables.","연구들은 두 변수 사이에 긍정적인 상관관계가 있음을 보여준다."],
[117,"★★★","New media have transcended traditional national boundaries.","새로운 미디어는 전통적인 국가 경계를 초월했다."],
[118,"★★★","Student representatives will be visiting classes with voting forms.","학생 대표들은 투표 양식을 가지고 각 반을 방문할 것이다."],
[119,"★★★","All of the assignments must be submitted in person to the faculty office.","모든 과제는 학부 사무실에 직접 제출해야 한다."],
[120,"★★★","Some people argue that education is not that important.","일부 사람들은 교육이 그렇게 중요하지 않다고 주장한다."],
[121,"★★★","It is really a comprehensive program that covers both theory and practice.","이것은 이론과 실제를 모두 다루는 매우 포괄적인 프로그램이다."],
[122,"★★★","The educational level is found to be related to social and economic background.","교육 수준은 사회적·경제적 배경과 관련이 있는 것으로 나타났다."],
[123,"★★★","The students have the options to live in residences or apartments.","학생들은 기숙사나 아파트에 거주하는 선택지를 가지고 있다."],
[124,"★★★","Organizational failure is considered from various perspectives in academic literature.","조직 실패는 학술 문헌에서 다양한 관점으로 다루어진다."],
[125,"★★★","Our view is that educational reforms have been inadequately implemented.","우리의 견해는 교육 개혁이 불충분하게 시행되었다는 것이다."],
[126,"★★★","The director of the gallery was grateful for the anonymous donation.","갤러리 관장은 익명의 기부에 감사했다."],
[127,"★★★","The most popular courses still have a few places left.","가장 인기 있는 강좌에도 아직 몇 자리가 남아 있다."],
[128,"★★★","Parents' talk to children tends to be simplified.","부모가 아이에게 하는 말은 단순화되는 경향이 있다."],
[129,"★★★","While some people regard it as reforming zeal, others regard it as recklessness.","어떤 사람들은 그것을 개혁적 열정으로 보지만, 다른 사람들은 무모함으로 본다."],
[130,"★★★","The massive accumulation of data was converted into a communicable argument.","방대한 데이터의 축적은 전달 가능한 논증으로 전환되었다."],
[131,"★★★","The application process may take longer than expected.","지원 절차는 예상보다 더 오래 걸릴 수 있다."],
[132,"★★★","Consumer confidence has a direct influence on sales.","소비자 신뢰는 매출에 직접적인 영향을 미친다."],
[133,"★★★","Statistical results should be described in different ways depending on circumstances.","통계 결과는 상황에 따라 다른 방식으로 설명되어야 한다."],
[134,"★★★","The key difference between courses is the kind of assessment.","강좌 간의 핵심적인 차이는 평가 방식이다."],
[135,"★★★","Human beings compete with other living things for resources and space.","인간은 자원과 공간을 놓고 다른 생물들과 경쟁한다."],
[136,"★★","There is probably life on other planets in the universe.","우주의 다른 행성에도 생명체가 있을 가능성이 있다."],
[137,"★★","Universities need to secure research funds for projects.","대학은 프로젝트를 위한 연구 자금을 확보해야 한다."],
[138,"★★","You must be able to work in a team.","팀 안에서 일할 수 있어야 한다."],
[139,"★★","We have a lecture in the morning on Thursday.","우리는 목요일 아침에 강의가 있다."],
[140,"★★","Designers need to keep up with the social trend.","디자이너들은 사회적 트렌드를 따라가야 한다."],
[141,"★★","Mixtures are defined as a compound of chemically separate parts.","혼합물은 화학적으로 분리된 부분들의 결합으로 정의된다."],
[142,"★★","You should provide examples to support your ideas and arguments.","자신의 생각과 주장을 뒷받침하기 위해 예시를 제시해야 한다."],
[143,"★★","The science library is currently located on the ground floor of the library.","과학 도서관은 현재 도서관 1층에 있다."],
[144,"★★","Economic development needs to be supported by the government.","경제 발전은 정부의 지원을 받을 필요가 있다."],
[145,"★★","The railway makes the long-distance travel possible for everyone.","철도는 누구에게나 장거리 여행을 가능하게 한다."],
[146,"★★","It may not mean that it is possible to solve the problem easily.","그것이 문제를 쉽게 해결할 수 있다는 의미는 아닐 수 있다."],
[147,"★★","Students are encouraged to think carefully about their accommodation needs.","학생들은 자신의 숙소 필요 사항을 신중하게 생각하도록 권장된다."],
[148,"★★","We can't consider any increase in our price at this stage.","현 단계에서는 가격 인상을 고려할 수 없다."],
[149,"★","The conference will be held on Thursday morning.","그 회의는 목요일 오전에 열릴 것이다."],
[150,"★","We are encouraged to write on each page.","우리는 각 페이지에 필기할 것을 권장받는다."],
[151,"★","Neuroscience is a compound of completely separate parts.","신경과학은 완전히 분리된 부분들의 결합이다."],
[152,"★","The professor will have a lecture in the class.","그 교수는 수업에서 강의를 할 것이다."],
[153,"★","Your boss wants you to finish this report by Monday.","당신의 상사는 당신이 월요일까지 이 보고서를 끝내기를 원한다."],
[154,"★","The students will meet their new teachers after summer vacation.","학생들은 여름 방학이 끝난 뒤 새로운 선생님들을 만날 것이다."],
[155,"★","There must be planets in the universe that can support life.","우주에는 생명을 지탱할 수 있는 행성들이 분명히 있을 것이다."],
[156,"★","The teacher explained the homework to the class.","교사는 학급 학생들에게 숙제를 설명했다."],
[157,"★","Reading widely is important for undergraduate study.","폭넓은 독서는 학부 과정 공부에 중요하다."],
[158,"★","Lecture outlines are available on the faculty board and internal website.","강의 개요는 학부 게시판과 내부 웹사이트에서 확인할 수 있다."],
[159,"★","Reading histories involves a level of careful selections.","역사를 읽는 것은 어느 정도의 신중한 선별을 필요로 한다."],
[160,"★","The celebrated theory is still the source of a great controversy.","그 유명한 이론은 여전히 큰 논쟁의 원천이다."],
[161,"★","The rise in the sea level indicates climate change.","해수면 상승은 기후 변화를 나타낸다."],
[162,"★","Information may soon disappear forever as fewer people are reading classical languages.","고전어를 읽는 사람이 줄어들면서 정보가 머지않아 영원히 사라질 수도 있다."],
[163,"★","A good architectural structure should be usable, durable and beautiful.","좋은 건축 구조는 사용 가능하고, 내구성이 있으며, 아름다워야 한다."],
[164,"★","Students who are successful have a good strategy for learning.","성공하는 학생들은 훌륭한 학습 전략을 가지고 있다."],
[165,"★","There is clearly a need for further research in this field.","이 분야에는 분명히 추가 연구가 필요하다."],
[166,"★","A group meeting will be held tomorrow in the library conference room.","내일 도서관 회의실에서 조별 모임이 열릴 것이다."],
[167,"★","Affordable housing is an important issue for all members of society.","저렴한 주택은 사회 모든 구성원에게 중요한 문제이다."]
].map(([id,stars,en,ko])=>({id,stars,en,ko,audio:`/wfd/WFD Oct 26 ${id}.mp3`}));